FROM node:14.15.3-alpine

WORKDIR /src

RUN apk add --no-cache make gcc g++ python && \
  yarn add --force bcrypt --build-from-source && \
  apk del make gcc g++ python

COPY ./api .

RUN rm -rf /src/node_modules

RUN  yarn install

CMD yarn start:dev