FROM node:14.15.3-alpine

WORKDIR /src

COPY ./api .

RUN rm -rf /src/node_modules

RUN apk add --no-cache make gcc g++ python && \
  yarn install && \
  yarn add --force bcrypt --build-from-source && \
  apk del make gcc g++ python

CMD yarn start:dev